baseurl = "rohany.github.io"
theme = "cocoa-eh"
builddrafts = true
canonifyurls = true
contentdir = "content"
languageCode = "en-US"
layoutdir = "layouts"
publishdir = "public"
author = "Rohan Yadav"
title = "Rohan Yadav"
disqusshortname = ""
pluralizelisttitles = false
disableKinds = ["taxonomy", "taxonomyTerm"]

# [permalinks]
# blog = "blog/:slug/"

[params]
dateform = "May 21, 2019"
dateformfull = "Mon Jan 2 2006 15:04:05 MST"
description = "Example blog"
# copyright = "Copyright © 2019 Rohan Yadav"
# copyrightUrl = "https://creativecommons.org/licenses/by-sa/4.0/"
logofile = "img/rohan_photo.jpg"
# faviconfile = "img/logo.png"
highlightjs = true
progressively = true
# share = true
# Share to googleplus, twitter, fb, linkedin by default
# disable by setting share_on_<social network> = false
# example: share_on_googleplus = false
latestpostcount = 5
scholar = "https://scholar.google.com/citations?user=75t_IX8AAAAJ&hl=en"
github = "rohany"
twitter = "brohanster"
# email = "rohandotyadav@gmail.com"
linkedin = "rohan-yadav-10455310b"
# social_banner = "img/banner.png"
usesmallsummarycard = true
posts_navigation = true
# issoHost = "comments.domain.tld:1234"
# githubRepo = "githubUsername/repositoryName/tree/master"
small_banner_logo = false

[params.colors]
identifier = "#527fc1f"
identifier_dark = "#1a3152"
trivial = "#6a7a8b"
foreground = "#181d2a"
background = "#f9f9f9"
background_dark = "#282a36"
code = "#87a5d2"
type = "#97d28b"
special = "#ffcb8d"
value = "#96c2d7"
statement = "#ff8e91"
